### ISSUE TITLE
[Glass Panel Variant] A Glass Panel wich is not checkered.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#466]

**Comment by ZombiePwner1** [comment]
This item will prevent glass bug transparencey

**Comment by Luke18033** [comment]
This should be an alternate version of the glass panel on clean style.

**Comment by Luke18033** [comment]
This would probably be better as a separate item, actually. Old Aperture and P1 would use hinges to attach the panel to the surface. You'd have to make a custom dirty/cracked version for Overgrown.

**Comment by Luke18033** [comment]
![20170311185423_1](https://cloud.githubusercontent.com/assets/19228201/23828612/78414d32-068c-11e7-9826-395c31940e5f.jpg)

**Comment by Luke18033** [comment]
I need to finish this...

**Comment by Luke18033** [comment]
Things that still need to be done:
* [ ] The entire embed for the double panel should be grating, having half of it as backpanels looks weird
* [ ] Rename double variant to just "double glass panel"
* [ ] Old Aperture variants need a new design (what though?)
* [ ] Update editor models and icons - entire bottom should be grating, and it needs style variants (#2026)
* [ ] Double panel needs a rescaled model for clean/overgrown (#2025)
* [ ] Should use the angled panel item class to allow placement in goo (#2024)
* [ ] Fix issues with P1 arms - visible gap (#2001), no hole in grating (#2000), maybe change it entirely to use pistons

**Comment by Konclan** [comment]
Wait why does this item have 2 issues open now?

**Comment by Luke18033** [comment]
Because they were originally suggested separately, I just put them both in the same package.

**Comment by Konclan** [comment]
Ah that makes sense, not really a duplicate then
