### ISSUE TITLE
Checklist of 3 improvements for "Bottomless Pit" before next pre release

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#777]
checklist of stuff that needs to be in next pre-release in bottomless pits

- [x] Ability to make Pits Deeper to make fall illusion look more realistic with correct generation of sides in maps such as Wheatley style...
- [ ] Forced Piller Generation on islands (single pillars), 3 sided parts and corners
- [ ] ability to place skybox texture on walls and ceilings so you can create the illusion of open test chambers like the Wheatley ones in the original game...

if we can get these three done, i should be able to design some pits for you in hammer like the clean, Wheatley, and p1 clean pit (not incinerator)

i have a idea for the overgrown pit, we would create multiple skyboxes and use code to randomly select one from the config file and each one would have something like a cement floor at the bottom that would be un even simular to how the caves where designed in the underground in hammer... then we would generate pillars and fill the rest with overgrown test chamber instances for the pit...

**Comment by ellingtonvengaboysmuseum** [comment]
this topic is no longer needed because my enhanced bottomless pit idea will solve pillar generation problems
